### ISSUE TITLE
not enough DAWG

### ISSUE THREAD

**Issue by ijo-amali** [Puppybytes/puppybytes.github.io#1]
# MORE DAWG

**Comment by Puppybytes** [comment]
Hey Amawi
Thanks for taking the time to write out an issue.
Unfortunately, the problem you described can't be replicated on any device I tried.
This might be a browser issue, try going into settings > general > advanced and toggling the dawg to on in firefox. 
Otherwise I'd recommend getting that dawg in you support program to resolve any further issues. 

I hope this has been sufficiently helpful.
